//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meta()
        {
            this.Oferta = new HashSet<Oferta>();
        }
    
        public int IdMeta { get; set; }
        public Nullable<long> MetaFormacion { get; set; }
        public Nullable<long> MetaTecnologia { get; set; }
        public Nullable<long> MetaTecnico { get; set; }
        public Nullable<long> MetaET { get; set; }
        public Nullable<long> MetaOtros { get; set; }
        public bool EstadoMeta { get; set; }
        public Nullable<long> MetaTGOApPasan { get; set; }
        public Nullable<long> MetaTCOApPasan { get; set; }
        public Nullable<long> MetaETApPasan { get; set; }
        public Nullable<long> MetaOTROApPasan { get; set; }
        public string MetaFecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
    }
}
