//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenaPlanningEntities : DbContext
    {
        public SenaPlanningEntities()
            : base("name=SenaPlanningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambiente> Ambientes { get; set; }
        public virtual DbSet<Area_Conocimiento> Area_Conocimiento { get; set; }
        public virtual DbSet<Ficha> Fichas { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Meta> Metas { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<Programa_Formacion> Programa_Formacion { get; set; }
        public virtual DbSet<Red_Conocimiento> Red_Conocimiento { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
